package NSHEPPWebsiteAutomation;

import static org.junit.Assert.*;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import NSHEPPWebsiteAutomation.NSHEPPAboutYouLinkChecked;
import NSHEPPWebsiteAutomation.NSHEPPEmployeeLinkChecked;
import NSHEPPWebsiteAutomation.NSHEPPHomePageLinkChecked;
import NSHEPPWebsiteAutomation.NSHEPPPublicationLinkChecked;
import NSHEPPWebsiteAutomation.NSHEPPEmployerLinkChecked;
import NSHEPPWebsiteAutomation.NSHEPPPensionerLinkChecked;

public class LinkChecker {
	private WebDriver driver;
	private String baseurl;
	private String baseurl1;
	private String baseurl2;
	private String baseurl3;
	private String baseurl4;
	private String baseurl5;
	private String baseurl6;
	private String baseurl7;
	private String baseurl8;
	private String baseurl9;
	private String baseurl10;
	private String baseurl11;
	private String baseurl118;
	private String baseurl22;
	private JavascriptExecutor js;



	@Before
	public void setUp() throws Exception {
		System.setProperty("webdriver.chrome.driver", "C:\\Users\\sdutta\\workspace\\libs\\driver\\chromedriver.exe");
		driver = new ChromeDriver();
		js = (JavascriptExecutor)driver;
		baseurl = "https://nshepp-development.azurewebsites.net/about";
		baseurl118 = "https://nshepp-development.azurewebsites.net/plan-highlights";
		baseurl22 = "https://nshepp-development.azurewebsites.net/contributions";
		baseurl3 = "https://nshepp-development.azurewebsites.net/spouse-beneficiary";
		baseurl4 = "https://nshepp-development.azurewebsites.net/joining";
		baseurl5 = "https://nshepp-development.azurewebsites.net/employment-changes";
		baseurl6 = "https://nshepp-development.azurewebsites.net/life-events";
		baseurl7 = "https://nshepp-development.azurewebsites.net/retiring";
		baseurl8 = "https://nshepp-development.azurewebsites.net/";
		baseurl9 = "https://nshepp-development.azurewebsites.net/publications";
		baseurl10 = "https://nshepp-mfatest.azurewebsites.net/employer-forms";
		baseurl1 = "https://nshepp-development.azurewebsites.net/plan-highlights/employers";
		baseurl2 = "https://nshepp-development.azurewebsites.net/pension-payments";
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
	}

	@After
	public void tearDown() throws Exception {
	}

	@Test
	public void test() throws InterruptedException {
		driver.get(baseurl);
		String navigateurl = "https://nshepp-development.azurewebsites.net/about";
		Thread.sleep(2000);
		NSHEPPAboutYouLinkChecked.Link1(driver);
		Thread.sleep(2000);
		NSHEPPAboutYouLinkChecked.Link2(driver);
		Thread.sleep(2000);
		NSHEPPAboutYouLinkChecked.Link3(driver);
		Thread.sleep(2000);
		String parentHandle = driver.getWindowHandle();
	    driver.switchTo().window(parentHandle);
	    Thread.sleep(2000);
	    NSHEPPAboutYouLinkChecked.Link4(driver);
        driver.switchTo().window(parentHandle);
        js.executeScript("window.scrollBy(0, -600);");
        Thread.sleep(2000);
        NSHEPPAboutYouLinkChecked.Link5(driver);
        driver.switchTo().window(parentHandle);
        js.executeScript("window.scrollBy(0, -600);");
        Thread.sleep(2000);
        NSHEPPAboutYouLinkChecked.Link6(driver);
        driver.switchTo().window(parentHandle);
        js.executeScript("window.scrollBy(0, -600);");
        Thread.sleep(2000);
        NSHEPPAboutYouLinkChecked.Link7(driver);
        driver.switchTo().window(parentHandle);
        js.executeScript("window.scrollBy(0, -600);");
        Thread.sleep(2000);
        NSHEPPAboutYouLinkChecked.Link8(driver);
        driver.switchTo().window(parentHandle);
        js.executeScript("window.scrollBy(0, -600);");
        Thread.sleep(2000);
        NSHEPPAboutYouLinkChecked.Link9(driver);
        driver.switchTo().window(parentHandle);
        js.executeScript("window.scrollBy(0, -600);");
        Thread.sleep(2000);
        NSHEPPAboutYouLinkChecked.Link10(driver);
        driver.switchTo().window(parentHandle);
        js.executeScript("window.scrollBy(0, -800);");
        Thread.sleep(2000);
        NSHEPPAboutYouLinkChecked.Link11(driver);
        driver.switchTo().window(parentHandle);
        js.executeScript("window.scrollBy(0, -700);");
        Thread.sleep(2000);
        NSHEPPAboutYouLinkChecked.Link12(driver);
        driver.switchTo().window(parentHandle);
        js.executeScript("window.scrollBy(0, -2000);");
        Thread.sleep(2000);
        NSHEPPAboutYouLinkChecked.Link13(driver);
        driver.switchTo().window(parentHandle);
        js.executeScript("window.scrollBy(0, -2000);");
        Thread.sleep(2000);
        NSHEPPAboutYouLinkChecked.Link14(driver);
        driver.switchTo().window(parentHandle);
        js.executeScript("window.scrollBy(0, -2000);");
        driver.quit();
		
	}
	@Test
	public void test1() throws InterruptedException {
		driver.get(baseurl118);
		String navigateurl = "https://nshepp-development.azurewebsites.net/plan-highlights";
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.PlanHighlightsLink1(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.PlanHighlightsLink2(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.PlanHighlightsLink3(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.PlanHighlightsLink4(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.PlanHighlightsLink5(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.PlanHighlightsLink6(driver);
		driver.navigate().to(navigateurl);
		String parentHandle = driver.getWindowHandle();
        driver.switchTo().window(parentHandle);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.PlanHighlightsLink7(driver);
		js.executeScript("window.scrollBy(0, -1200);");
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.PlanHighlightsLink8(driver);
		js.executeScript("window.scrollBy(0, -1500);");
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.PlanHighlightsLink9(driver);
		js.executeScript("window.scrollBy(0, -1700);");
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.PlanHighlightsLink10(driver);
		driver.navigate().to(navigateurl);
		String parentHandle1 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle1);
		//js.executeScript("window.scrollBy(0, -1700);");
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.PlanHighlightsLink11(driver);
		driver.navigate().to(navigateurl);
		String parentHandle11 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle11);
		js.executeScript("window.scrollBy(0, -1700);");
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.PlanHighlightsLink12(driver);
		js.executeScript("window.scrollBy(0, -1900);");
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.PlanHighlightsLink13(driver);
		js.executeScript("window.scrollBy(0, -1900);");
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.PlanHighlightsLink14(driver);
		js.executeScript("window.scrollBy(0, -1900);");
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.PlanHighlightsLink15(driver);
		driver.navigate().to(navigateurl);
		String parentHandle111 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle111);
		js.executeScript("window.scrollBy(0, -2100);");
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.PlanHighlightsLink16(driver);
		js.executeScript("window.scrollBy(0, -2300);");
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.PlanHighlightsLink17(driver);
		js.executeScript("window.scrollBy(0, -2500);");
		driver.quit();
	}
	@Test
	public void test2() throws InterruptedException {
		driver.get(baseurl22);
		String navigateurl = "https://nshepp-development.azurewebsites.net/contributions";
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.ContributionsLink1(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.ContributionsLink2(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.ContributionsLink3(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.ContributionsLink4(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.ContributionsLink5(driver);
		Thread.sleep(2000);
		driver.quit();
	}
	@Test
	public void test3() throws InterruptedException {
		driver.get(baseurl3);
		String navigateurl = "https://nshepp-development.azurewebsites.net/spouse-beneficiary";
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.NamingaBenLink1(driver);
		driver.navigate().to(navigateurl);
		String parentHandle1 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle1);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.NamingaBenLink2(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.NamingaBenLink3(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.NamingaBenLink4(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.NamingaBenLink5(driver);
		Thread.sleep(2000);
		driver.quit();
	}
	@Test
	public void test4() throws InterruptedException {
		driver.get(baseurl4);
		String navigateurl = "https://nshepp-development.azurewebsites.net/joining";
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.JoiningtheplanLink1(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.JoiningtheplanLink2(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.JoiningtheplanLink3(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.JoiningtheplanLink4(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.JoiningtheplanLink5(driver);
		driver.navigate().to(navigateurl);
		String parentHandle1 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle1);
		Thread.sleep(2000);
		driver.quit();
		
	}
	@Test
	public void test5() throws InterruptedException {
		driver.get(baseurl5);
		String navigateurl = "https://nshepp-development.azurewebsites.net/employment-changes";
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.EmploymentchangesLink1(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.EmploymentchangesLink2(driver);
		driver.navigate().to(navigateurl);
		String parentHandle1 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle1);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.EmploymentchangesLink3(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.EmploymentchangesLink4(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.EmploymentchangesLink5(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.EmploymentchangesLink6(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.EmploymentchangesLink7(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.EmploymentchangesLink8(driver);
		Thread.sleep(2000);
		driver.quit();
			
	}
	@Test
	public void test6() throws InterruptedException {
		driver.get(baseurl6);
		String navigateurl = "https://nshepp-development.azurewebsites.net/life-events";
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.LifeEventsLink1(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.LifeEventsLink2(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.LifeEventsLink3(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.LifeEventsLink4(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.LifeEventsLink5(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.LifeEventsLink6(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.LifeEventsLink7(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.LifeEventsLink8(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.LifeEventsLink9(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.LifeEventsLink10(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.LifeEventsLink11(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.LifeEventsLink12(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.LifeEventsLink13(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.LifeEventsLink14(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.LifeEventsLink15(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.LifeEventsLink16(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.LifeEventsLink17(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.LifeEventsLink18(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.LifeEventsLink19(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.LifeEventsLink20(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.LifeEventsLink21(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.LifeEventsLink22(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.LifeEventsLink23(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.LifeEventsLink24(driver);
		Thread.sleep(2000);
		driver.quit();
			
	}
	@Test
	public void test7() throws InterruptedException {
		driver.get(baseurl7);
		String navigateurl = "https://nshepp-development.azurewebsites.net/retiring";
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink1(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink2(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink3(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink4(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink5(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink6(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink7(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink8(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink9(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink10(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink11(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink12(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink13(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink14(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink15(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink16(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink17(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink18(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink19(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink20(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink21(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink22(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink23(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink24(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink25(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink26(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink27(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink28(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink29(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink30(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink31(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink32(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink33(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink34(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink35(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink36(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink37(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink38(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink39(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink40(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink41(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink42(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink43(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink44(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink45(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink46(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink47(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink48(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink49(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink50(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink51(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink52(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink53(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink54(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink55(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink56(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink57(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink58(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink59(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink60(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink61(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink62(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink63(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink64(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink65(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink66(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink67(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink68(driver);
		Thread.sleep(2000);
		NSHEPPEmployeeLinkChecked.RetiringLink69(driver);
		Thread.sleep(2000);
		driver.quit();
	}
	@Test
	public void test8() throws InterruptedException, IOException {
		driver.get(baseurl8);
		String navigateurl = "https://nshepp-development.azurewebsites.net/";
		Thread.sleep(2000);
		NSHEPPHomePageLinkChecked.HomePageLink1(driver);
		driver.navigate().to(navigateurl);
		String parentHandle1 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle1);
        Thread.sleep(2000);
        NSHEPPHomePageLinkChecked.HomePageImage1(driver);
		driver.navigate().to(navigateurl);
		String parentHandle2 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle2);
        Thread.sleep(2000);
        NSHEPPHomePageLinkChecked.HomePageLink2(driver);
		Thread.sleep(2000);
		NSHEPPHomePageLinkChecked.HomePageImage2(driver);
		Thread.sleep(2000);
		NSHEPPHomePageLinkChecked.HomePageLink3(driver);
		driver.navigate().to(navigateurl);
		String parentHandle3 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle3);
        Thread.sleep(2000);
    	NSHEPPHomePageLinkChecked.HomePageImage3(driver);
		driver.navigate().to(navigateurl);
		String parentHandle4 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle4);
        Thread.sleep(2000);
        NSHEPPHomePageLinkChecked.HomePageLink4(driver);
		driver.navigate().to(navigateurl);
		String parentHandle5 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle5);
        Thread.sleep(2000);
    	NSHEPPHomePageLinkChecked.HomePageImage4(driver);
		driver.navigate().to(navigateurl);
		String parentHandle6 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle6);
        Thread.sleep(2000);
        NSHEPPHomePageLinkChecked.HomePageLink5(driver);
		driver.navigate().to(navigateurl);
		String parentHandle7 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle7);
        Thread.sleep(2000);
        NSHEPPHomePageLinkChecked.HomePageLink6(driver);
        Thread.sleep(2000);
        NSHEPPHomePageLinkChecked.HomePageLink7(driver);
        Thread.sleep(2000);
        driver.quit();
	}
	@Test
	public void test9() throws InterruptedException, IOException {
		driver.get(baseurl9);
		String navigateurl = "https://nshepp-development.azurewebsites.net/publications";
		Thread.sleep(2000);
		NSHEPPPublicationLinkChecked.Link1(driver);
        Thread.sleep(2000);
    	NSHEPPPublicationLinkChecked.Link2(driver);
		driver.navigate().to(navigateurl);
		String parentHandle1 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle1);
        Thread.sleep(2000);
        NSHEPPPublicationLinkChecked.Link3(driver);
        Thread.sleep(2000);
        NSHEPPPublicationLinkChecked.Link4(driver);
        Thread.sleep(2000);
        NSHEPPPublicationLinkChecked.Link5(driver);
        Thread.sleep(2000);
        NSHEPPPublicationLinkChecked.Link6(driver);
        driver.navigate().to(navigateurl);
		String parentHandle2 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle2);
        Thread.sleep(2000);
        NSHEPPPublicationLinkChecked.Link7(driver);
        driver.navigate().to(navigateurl);
		String parentHandle3 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle3);
        Thread.sleep(2000);
        driver.quit();
	}
	@Test
	public void test10() throws InterruptedException, IOException {
		driver.get(baseurl10);
		String navigateurl = "https://nshepp-mfatest.azurewebsites.net/employer-forms";
		Thread.sleep(2000);
		NSHEPPEmployerLinkChecked.FormsanddocumentsLink1(driver);
		driver.navigate().to(navigateurl);
		String parentHandle1 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle1);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.FormsanddocumentsLink2(driver);
		driver.navigate().to(navigateurl);
		String parentHandle2 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle2);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.FormsanddocumentsLink3(driver);
		driver.navigate().to(navigateurl);
		String parentHandle3 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle3);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.FormsanddocumentsLink4(driver);
		driver.navigate().to(navigateurl);
		String parentHandle4 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle4);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.FormsanddocumentsLink5(driver);
    	driver.navigate().to(navigateurl);
		String parentHandle5 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle5);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.FormsanddocumentsLink6(driver);
    	driver.navigate().to(navigateurl);
		String parentHandle6 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle6);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.FormsanddocumentsLink7(driver);
    	driver.navigate().to(navigateurl);
		String parentHandle7 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle7);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.FormsanddocumentsLink8(driver);
    	driver.navigate().to(navigateurl);
		String parentHandle8 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle8);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.FormsanddocumentsLink9(driver);
    	driver.navigate().to(navigateurl);
		String parentHandle9 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle9);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.FormsanddocumentsLink10(driver);
    	driver.navigate().to(navigateurl);
		String parentHandle10 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle10);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.FormsanddocumentsLink11(driver);
    	driver.navigate().to(navigateurl);
		String parentHandle11 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle11);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.FormsanddocumentsLink12(driver);
    	driver.navigate().to(navigateurl);
		String parentHandle12 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle12);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.FormsanddocumentsLink13(driver);
    	driver.navigate().to(navigateurl);
		String parentHandle13 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle13);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.FormsanddocumentsLink14(driver);
    	driver.navigate().to(navigateurl);
		String parentHandle14 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle14);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.FormsanddocumentsLink15(driver);
    	driver.navigate().to(navigateurl);
		String parentHandle15 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle15);
        Thread.sleep(2000);
        driver.quit();
     
       
    	
	}
	@Test
	public void test11() throws InterruptedException, IOException {
		driver.get(baseurl1);
		String navigateurl = "https://nshepp-development.azurewebsites.net/plan-highlights/employers";
		Thread.sleep(2000);
		NSHEPPEmployerLinkChecked.PlanHighlights1(driver);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.PlanHighlights2(driver);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.PlanHighlights3(driver);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.PlanHighlights4(driver);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.PlanHighlights5(driver);
    	driver.navigate().to(navigateurl);
		String parentHandle = driver.getWindowHandle();
        driver.switchTo().window(parentHandle);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.PlanHighlights6(driver);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.PlanHighlights7(driver);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.PlanHighlights8(driver);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.PlanHighlights9(driver);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.PlanHighlights10(driver);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.PlanHighlights11(driver);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.PlanHighlights12(driver);
    	driver.navigate().to(navigateurl);
		String parentHandle1 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle1);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.PlanHighlights13(driver);
    	driver.navigate().to(navigateurl);
		String parentHandle2 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle2);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.PlanHighlights14(driver);
    	driver.navigate().to(navigateurl);
		String parentHandle3 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle3);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.PlanHighlights15(driver);
        Thread.sleep(2000);
        NSHEPPEmployerLinkChecked.PlanHighlights16(driver);
        Thread.sleep(2000);
        driver.quit();
    	
	}
	@Test
	public void test12() throws InterruptedException, IOException {
		driver.get(baseurl2);
		String navigateurl = "https://nshepp-development.azurewebsites.net/pension-payments";
		Thread.sleep(2000);
		NSHEPPPensionerLinkChecked.PensionPaymentsLink1(driver);
		driver.navigate().to(navigateurl);
		String parentHandle2 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle2);
        Thread.sleep(2000);
        NSHEPPPensionerLinkChecked.PensionPaymentsLink2(driver);
		driver.navigate().to(navigateurl);
		String parentHandle3 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle3);
        Thread.sleep(2000);
        NSHEPPPensionerLinkChecked.PensionPaymentsLink3(driver);
		driver.navigate().to(navigateurl);
		String parentHandle4 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle4);
        Thread.sleep(2000);
        NSHEPPPensionerLinkChecked.PensionPaymentsLink4(driver);
      	driver.navigate().to(navigateurl);
      	String parentHandle5 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle5);
        Thread.sleep(2000);
        NSHEPPPensionerLinkChecked.PensionPaymentsLink5(driver);
        Thread.sleep(2000);
        NSHEPPPensionerLinkChecked.PensionPaymentsLink6(driver);
		driver.navigate().to(navigateurl);
		String parentHandle6 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle6);
        Thread.sleep(2000);
        NSHEPPPensionerLinkChecked.PensionPaymentsLink7(driver);
		driver.navigate().to(navigateurl);
		String parentHandle7 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle7);
        Thread.sleep(2000);
        NSHEPPPensionerLinkChecked.PensionPaymentsLink8(driver);
		driver.navigate().to(navigateurl);
		String parentHandle8 = driver.getWindowHandle();
        driver.switchTo().window(parentHandle8);
        Thread.sleep(2000);
        NSHEPPPensionerLinkChecked.PensionPaymentsLink9(driver);
        Thread.sleep(2000);
        NSHEPPPensionerLinkChecked.PensionPaymentsLink10(driver);
        Thread.sleep(2000);
        driver.quit();
              
        
       
	}
}
